### ISSUE TITLE
Does this work for st3 v3083? 

### ISSUE THREAD

**Issue by oglops** [skuroda/ImprovedMacros#1]
I installed it manually, but it has no effect, using sublime 3 v3083, in console I saw

```
reloading plugin ImprovedMacros,ImprovedMacros
```

and there is no error. but it's not showing in Preferences -> package settings menu. and my added hotkey does not work. I added the hotkey example in readme.

**Comment by skuroda** [comment]
Hi @oglops, did it end up working for you?  What can I add, if anything, to make it a bit more clear?
